//! The baked per-blockstate table (`assets/blockprops.bin`, format `XBP1`).
//!
//! Two jobs in one artifact:
//!
//! 1. **Id resolver.** zvcr stores blocks as global blockstate ids in
//!    `Block.BLOCK_STATE_REGISTRY` order. This table is generated by walking
//!    that same registry, so index == zvcr id, and it can name any state and
//!    emit the NBT Xaero's palette expects.
//! 2. **Behaviour source.** Xaero's column algorithm asks the game a dozen
//!    questions per block (map colour, render shape, light dampening, fluid
//!    state, ...). Those answers live in Minecraft's code, not its data files,
//!    so they are extracted once by running against the real jar
//!    (`tools/xaero-blockprops`) rather than guessed from block names.
//!
//! The generator cross-checks against the world download's own copy of the
//! registry: all 27 866 state names and light levels agree, which is what
//! makes the shared id space safe to rely on.

/// Flag bits — must stay in step with `tools/xaero-blockprops/BlockProps.java`.
pub mod flag {
    pub const AIR: u32 = 1 << 0;
    pub const RENDER_INVISIBLE: u32 = 1 << 1;
    pub const HAS_MAP_COLOR: u32 = 1 << 2;
    pub const FLUID_WATER: u32 = 1 << 3;
    pub const FLUID_LAVA: u32 = 1 << 4;
    pub const LIQUID_BLOCK: u32 = 1 << 5;
    pub const CAN_BE_REPLACED: u32 = 1 << 6;
    pub const IGNITED_BY_LAVA: u32 = 1 << 7;
    pub const PUSH_DESTROY: u32 = 1 << 8;
    pub const TRANSLUCENT_LAYER: u32 = 1 << 9;
    pub const SHAPE_FULL_BLOCK: u32 = 1 << 10;
    pub const TRANSPARENT_CLASS: u32 = 1 << 11;
    pub const HALF_TRANSP_CLASS: u32 = 1 << 12;
    pub const DOUBLE_PLANT: u32 = 1 << 13;
    pub const FLOWERISH: u32 = 1 << 14;
    pub const GRASS_BLOCK: u32 = 1 << 15;
    pub const WATER_BLOCK: u32 = 1 << 16;
    pub const TORCH: u32 = 1 << 17;
    pub const SHORT_GRASS: u32 = 1 << 18;
    pub const GLASS_OR_PANE: u32 = 1 << 19;
    pub const CAN_OCCLUDE: u32 = 1 << 20;
    pub const FLUID_TRANSLUCENT: u32 = 1 << 21;
    pub const TAG_LEAVES: u32 = 1 << 22;
}

#[derive(Debug, Clone, Copy)]
pub struct StateRow {
    pub flags: u32,
    /// `getLightEmission()` — also drives the pixel's glow bit.
    pub emission: u8,
    /// `getLightBlock()` (`getLightDampening` in newer Minecraft): how much
    /// light the block eats, which is what overlay opacity accumulates.
    pub light_block: u8,
    /// Index into `blocks`; identity comparisons in the algorithm are on the
    /// *block*, not the state, exactly as the mod does them.
    pub block: u16,
    /// State id of `getFluidState().createLegacyBlock()` — Xaero's
    /// `fluidToBlock`. Air's id when the block holds no fluid.
    pub fluid_legacy: u32,
    props: (u32, u8),
}

pub struct BlockProps {
    mc_version: String,
    blocks: Vec<String>,
    props: Vec<String>,
    prop_idx: Vec<u16>,
    states: Vec<StateRow>,
    /// `NbtIo.write(NbtUtils.writeBlockState(state))` bytes per state, built
    /// once at load: the region encoder re-emits these verbatim.
    nbt: Vec<Vec<u8>>,
    names: Vec<String>,
    air: u32,
}

impl BlockProps {
    pub fn parse(bytes: &[u8]) -> Result<BlockProps, String> {
        let mut p = P { b: bytes, i: 0 };
        if p.take(4)? != b"XBP1" {
            return Err("bad magic (expected XBP1)".into());
        }
        let fmt = p.u16()?;
        if fmt != 1 {
            return Err(format!("unsupported blockprops format {fmt}"));
        }
        let mc_version = p.str()?;
        let nblocks = p.u32()? as usize;
        let mut blocks = Vec::with_capacity(nblocks);
        for _ in 0..nblocks {
            blocks.push(p.str()?);
        }
        let nprops = p.u32()? as usize;
        let mut props = Vec::with_capacity(nprops);
        for _ in 0..nprops {
            props.push(p.str()?);
        }
        let nfluid = p.u32()? as usize;
        let mut fluid_legacy = Vec::with_capacity(nfluid);
        for _ in 0..nfluid {
            fluid_legacy.push(p.u32()?);
        }
        let nstates = p.u32()? as usize;
        let mut states = Vec::with_capacity(nstates);
        let mut prop_idx: Vec<u16> = Vec::new();
        for id in 0..nstates {
            let flags = p.u32()?;
            let emission = p.u8()?;
            let light_block = p.u8()?;
            let block = p.u16()?;
            let fluid = p.u8()? as usize;
            let n = p.u8()?;
            let start = prop_idx.len() as u32;
            for _ in 0..n {
                prop_idx.push(p.u16()?);
            }
            if block as usize >= nblocks {
                return Err(format!("state {id}: block index {block} out of range"));
            }
            let fluid_legacy = *fluid_legacy
                .get(fluid)
                .ok_or_else(|| format!("state {id}: fluid index {fluid} out of range"))?;
            states.push(StateRow {
                flags,
                emission,
                light_block,
                block,
                fluid_legacy,
                props: (start, n),
            });
        }
        if p.i != bytes.len() {
            return Err(format!("{} trailing bytes", bytes.len() - p.i));
        }
        for (id, s) in states.iter().enumerate() {
            for k in 0..s.props.1 as usize {
                let idx = prop_idx[s.props.0 as usize + k] as usize;
                if idx >= nprops {
                    return Err(format!("state {id}: property index {idx} out of range"));
                }
            }
        }

        let mut bp = BlockProps {
            mc_version,
            blocks,
            props,
            prop_idx,
            states,
            nbt: Vec::new(),
            names: Vec::new(),
            air: 0,
        };
        bp.nbt = (0..nstates as u32).map(|id| bp.build_nbt(id)).collect();
        bp.names = (0..nstates as u32).map(|id| bp.build_name(id)).collect();
        // Air is the algorithm's "found nothing" state; resolve it once rather
        // than trusting it to sit at id 0.
        bp.air = (0..nstates as u32)
            .find(|&id| bp.flags(id) & flag::AIR != 0 && bp.states[id as usize].props.1 == 0)
            .ok_or("no air state in table")?;
        Ok(bp)
    }

    pub fn mc_version(&self) -> &str {
        &self.mc_version
    }
    pub fn len(&self) -> usize {
        self.states.len()
    }
    pub fn is_empty(&self) -> bool {
        self.states.is_empty()
    }
    /// Id of `minecraft:air`, the state written when a column has no surface.
    pub fn air(&self) -> u32 {
        self.air
    }

    #[inline]
    pub fn row(&self, id: u32) -> &StateRow {
        // Out-of-range ids mean the file was written by a different Minecraft
        // version than the table; treat them as air rather than panicking on
        // one bad region in a 300 000-region run.
        self.states
            .get(id as usize)
            .unwrap_or(&self.states[self.air as usize])
    }
    #[inline]
    pub fn flags(&self, id: u32) -> u32 {
        self.row(id).flags
    }
    #[inline]
    pub fn block_of(&self, id: u32) -> u16 {
        self.row(id).block
    }
    #[inline]
    pub fn emission(&self, id: u32) -> u8 {
        self.row(id).emission
    }
    #[inline]
    pub fn light_block(&self, id: u32) -> u8 {
        self.row(id).light_block
    }
    #[inline]
    pub fn fluid_legacy(&self, id: u32) -> u32 {
        self.row(id).fluid_legacy
    }
    #[inline]
    pub fn has_fluid(&self, id: u32) -> bool {
        self.flags(id) & (flag::FLUID_WATER | flag::FLUID_LAVA) != 0
    }
    /// `state.isAir()`, which in vanilla holds for exactly the `AirBlock`
    /// states (air, cave air, void air) the algorithm's `instanceof AirBlock`
    /// tests select. Also the `WORLD_SURFACE` heightmap predicate, negated.
    #[inline]
    pub fn is_air(&self, id: u32) -> bool {
        self.flags(id) & flag::AIR != 0
    }
    pub fn name(&self, id: u32) -> &str {
        self.names
            .get(id as usize)
            .map(|s| s.as_str())
            .unwrap_or("minecraft:air")
    }
    /// Registry name without properties — what the renderer's colour table and
    /// Xaero's palette both key on.
    pub fn block_name(&self, id: u32) -> &str {
        &self.blocks[self.row(id).block as usize]
    }
    /// Raw `NbtIo` bytes for the state palette entry.
    pub fn nbt(&self, id: u32) -> &[u8] {
        self.nbt
            .get(id as usize)
            .unwrap_or(&self.nbt[self.air as usize])
    }

    fn build_name(&self, id: u32) -> String {
        let row = self.states[id as usize];
        let mut s = self.blocks[row.block as usize].clone();
        if row.props.1 > 0 {
            s.push('[');
            for k in 0..row.props.1 as usize {
                if k > 0 {
                    s.push(',');
                }
                s.push_str(&self.props[self.prop_idx[row.props.0 as usize + k] as usize]);
            }
            s.push(']');
        }
        s
    }

    /// `NbtIo.write(NbtUtils.writeBlockState(state), out)`: a named root
    /// compound with an empty name, holding `Name` and, when the state has
    /// any, a `Properties` sub-compound of string values.
    ///
    /// The game's own writer inherits `CompoundTag`'s hash order for these
    /// keys; we emit `Name` first, then `Properties`, deterministically. The
    /// reader skims by key, so the difference is invisible — but it does mean
    /// bytes need not match a game-written palette entry for the same state.
    fn build_nbt(&self, id: u32) -> Vec<u8> {
        const TAG_END: u8 = 0;
        const TAG_STRING: u8 = 8;
        const TAG_COMPOUND: u8 = 10;
        fn put_str(out: &mut Vec<u8>, s: &str) {
            // Every block, property and value name in Minecraft is ASCII, so
            // Java's modified UTF-8 and UTF-8 coincide here.
            out.extend_from_slice(&(s.len() as u16).to_be_bytes());
            out.extend_from_slice(s.as_bytes());
        }
        fn put_string_entry(out: &mut Vec<u8>, key: &str, value: &str) {
            out.push(TAG_STRING);
            put_str(out, key);
            put_str(out, value);
        }

        let row = self.states[id as usize];
        let mut out = Vec::with_capacity(64);
        out.push(TAG_COMPOUND);
        out.extend_from_slice(&0u16.to_be_bytes()); // root tag name: empty
        put_string_entry(&mut out, "Name", &self.blocks[row.block as usize]);
        if row.props.1 > 0 {
            out.push(TAG_COMPOUND);
            put_str(&mut out, "Properties");
            for k in 0..row.props.1 as usize {
                let token = &self.props[self.prop_idx[row.props.0 as usize + k] as usize];
                let (key, value) = token
                    .split_once('=')
                    .expect("property token is always key=value");
                put_string_entry(&mut out, key, value);
            }
            out.push(TAG_END);
        }
        out.push(TAG_END);
        out
    }
}

struct P<'a> {
    b: &'a [u8],
    i: usize,
}

impl<'a> P<'a> {
    fn take(&mut self, n: usize) -> Result<&'a [u8], String> {
        if self.b.len() - self.i < n {
            return Err("truncated blockprops table".into());
        }
        let s = &self.b[self.i..self.i + n];
        self.i += n;
        Ok(s)
    }
    fn u8(&mut self) -> Result<u8, String> {
        Ok(self.take(1)?[0])
    }
    fn u16(&mut self) -> Result<u16, String> {
        let b = self.take(2)?;
        Ok(u16::from_be_bytes([b[0], b[1]]))
    }
    fn u32(&mut self) -> Result<u32, String> {
        let b = self.take(4)?;
        Ok(u32::from_be_bytes([b[0], b[1], b[2], b[3]]))
    }
    fn str(&mut self) -> Result<String, String> {
        let n = self.u16()? as usize;
        let b = self.take(n)?;
        String::from_utf8(b.to_vec()).map_err(|e| e.to_string())
    }
}
